name: "Check all packages version"
description: "Check all packages version"

runs:
  using: "composite"
  steps:
    - name: checking_changelog_format
      shell: bash
      id: checking_changelog_format
      run:  ${{ github.action_path }}/.github/00-Scripts/checking_changelog_format.sh

    - name: checking_version_release
      shell: bash
      id: checking_version_release
      run:  ${{ github.action_path }}/.github/00-Scripts/checking_version_release.sh

    - name: checking_sequencer_config
      shell: bash
      id: checking_sequencer_config
      run:  ${{ github.action_path }}/.github/00-Scripts/checking_sequencer_config.sh
