name: checking_changelog_format

on:
  workflow_call:
    outputs:
      status:
        description: "Status"
        value: ${{ jobs.checking_changelog_format.outputs.status }}

jobs:
  checking_changelog_format:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.status_id.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checking changelog format
        id: changelog_script_id
        continue-on-error: true
        run: tdedieuDF/actions/.github/00-Scripts/checking_changelog_format.sh

      - name: Output status
        if: ${{ steps.changelog_script_id.outcome == 'failure' }}
        id: status_id
        run: |
          echo 'status<<EOF' >> $GITHUB_OUTPUT
          echo "$(cat err_${{ github.job }}.log)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
