name: checking_sequencer_config

on:
  workflow_call:
    outputs:
      status:
        description: "Status"
        value: ${{ jobs.checking_sequencer_config.outputs.output1 }}

jobs:
  checking_sequencer_config:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.status_id.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checking sequencer config
        id: sequencer_script_id
        continue-on-error: true
        run: .github/00-Scripts/checking_sequencer_config.sh

      - name: Output status
        if: ${{ steps.sequencer_script_id.outcome == 'failure' }}
        id: status_id
        run: |
          echo 'status<<EOF' >> $GITHUB_OUTPUT
          echo "$(cat err_${{ github.job }}.log)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
