name: main

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checking_changelog_format:
    name: checking_changelog_format
    uses: ./.github/workflows/checking_changelog_format.yml

  checking_version_release:
    name: checking_version_release
    uses: ./.github/workflows/checking_version_release.yml

  checking_sequencer_config:
    name: checking_sequencer_config
    uses: ./.github/workflows/checking_sequencer_config.yml

  request_changes:
    needs:
      [
        checking_changelog_format,
        checking_version_release,
        checking_sequencer_config,
      ]
    name: Request changes
    uses: ./.github/workflows/request_changes.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      conclusion: ${{ needs.checking_changelog_format.outputs.status == null &&
        needs.checking_version_release.outputs.status == null &&
        needs.checking_sequencer_config.outputs.status == null }}
      status: "${{ needs.checking_changelog_format.outputs.status }} \r
        ${{ needs.checking_version_release.outputs.status }} \r
        ${{ needs.checking_sequencer_config.outputs.status }}"
        
